### ISSUE TITLE
Problem in Deployment CWYD

### ISSUE THREAD

**Issue by Vinay-Microsoft** [Azure-Samples/chat-with-your-data-solution-accelerator#1434] opened 2024-10-22 17:01 UTC
# Describe the bug
Problem in Deployment. Logging this Issue on behalf of Youssef Naggar

# Expected behavior

I am currently working on deploying the "Chat with Your Data" solution accelerator from the template provided in the GitHub repository: [Azure-Samples/chat-with-your-data-solution-accelerator](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FAzure-Samples%2Fchat-with-your-data-solution-accelerator&data=05%7C02%7Cv-vinayshar%40microsoft.com%7C509d093ed8344db028e808dcf2ace97c%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638652071743984236%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=f%2FikP9GvG7ArhAC8bO%2Fr%2F%2FoDwwnlslw7gHpIxDxtI8Q%3D&reserved=0). However, I encountered an authentication error during the deployment process, which is preventing me from moving forward.

Below, you will find the screenshots of the specific error I encountered.

![image](https://github.com/user-attachments/assets/b0e39bf0-44c8-4f55-a58b-c70cb492cd4d)

Could you kindly assist in identifying the root cause of this issue or provide any documentation or steps that I might have missed? I appreciate your support in resolving this.

Looking forward to your prompt response.

**Comment by Prasanjeet-Microsoft** [comment] 2024-10-22 17:50
Hello,

Could you please check the link below, follow the steps provided, and let us know the result?
https://github.com/Azure-Samples/chat-with-your-data-solution-accelerator/blob/main/docs/web-apps.md#add-authentication-in-azure-app-service-configuration

Thank you.

**Comment by UtkarshMishra-Microsoft** [comment] 2024-10-24 14:10
Hello,

**Key points followed in troubleshooting**

**Permission Issue:**

The app does not currently have the required permissions to run. These permissions were temporarily added during troubleshooting.
**Redeployment Steps:**

To address the issue, redeploy the "Chat with Your Data" (CWYD) accelerator with the necessary 18 services in your resource group.
The required services will be included automatically as part of the one-click deployment process. however, it was not working.
**Pre-Redeployment Check:**

Before redeployment, check all the services have required permission at resource group level and also at subscription level.
Region Snapshot:

A snapshot of the region has been shared to assist with selecting the appropriate regions for deployment.
Current Status & Observations:

Despite following the above steps, the issue persists.
Root Cause Identified So Far: The VM service is failing during deployment, and further troubleshooting is required to investigate the issue in detail.

Next Steps & Meeting:

The team will reconnect with you as per the scheduled time shared earlier. An invitation has been sent for the meeting.

Thanks

**Comment by Prasannakatakam-Microsoft** [comment] 2024-10-25 11:11
User attempted to trigger a new deployment, now deployment successful, But the app service encountered authentication issues.

**Comment by Prasanjeet-Microsoft** [comment] 2024-10-28 05:38
The user wasn't available to connect again on Friday, October 25th, so they asked to schedule the meeting for Monday, October 28th. We have a meeting with the user today.

**Comment by Prasanjeet-Microsoft** [comment] 2024-10-30 12:00
Hello,

I connected with the user on Teams and got to know that he hasn't created the Azure support request yet. I asked him to let me know his availability today since we need to discuss an alternative approach for a potential solution. He said that he will ping me once he is available.

Thank You.

**Comment by Vinay-Microsoft** [comment] 2024-10-31 22:06
Following is the update on this Issue

Hi All,

 

As you know, Chat With Your Data requires authentication to be integrated into the App Service. We're encountering the following issues with some customers

 

Issue with other tenant end users:

Create a new App Registration is Disabled when they redirect Resource Group -> App Service -> Authentication -> Add Provider -> Choose Identity Provider


Workaround:

We followed the steps outlined in the Research Assistant accelerator for this scenario:
Microsoft Entra ID -> App Registrations -> New Registration
 

However, we encountered an issue: the Service Tree ID field is mandatory, and we're unsure where to obtain it, leaving the user blocked.

 

We would appreciate your suggestions regarding the Service Tree ID.

 

Screenshot:



 

Thanks,
Roopan

**Comment by Prasanjeet-Microsoft** [comment] 2024-11-04 07:00
Following is the update on this Issue

As you know, Chat With Your Data requires authentication to be integrated into the App Service. We're encountering the following issues with some customers

Issue with other tenant end users:
Create a new App Registration is Disabled when they redirect Resource Group -> App Service -> Authentication -> Add Provider -> Choose Identity Provider

Workaround:
We followed the steps outlined in the Research Assistant accelerator for this scenario:
Microsoft Entra ID -> App Registrations -> New Registration

However, we encountered an issue: the Service Tree ID field is mandatory, and we're unsure where to obtain it, leaving the user blocked and currently waiting to get more information from MS.

**Comment by Prasanjeet-Microsoft** [comment] 2024-11-06 16:51
Hello,

We received feedback from the Microsoft team advising that all sellers should avoid using the Microsoft tenant. Instead, they should use CDX, FDPO shared tenant, or individual Managed User tenants. Both production and non-production Microsoft tenant subscriptions will be heavily restricted, especially with the new SFI policies implemented over the past year.

**The issue was that the end user was utilizing a non-production Microsoft tenant, which caused a blockage and prevented app registration due to a Service Tree ID issue.**

**The end user has since switched their subscription to an external one, which resolved the problem. They can now register the app, complete the deployment and access the web app without any issues.**

Thank You.

**Comment by Prasanjeet-Microsoft** [comment] 2024-11-07 06:05
Hello @Vinay-Microsoft , Since the user can now register the app, complete the deployment process and access the web app without any issues, I am closing this issue.

Thank you.

**Closed by Prasanjeet-Microsoft** 2024-11-07 06:05 UTC
Labels: bug
