### ISSUE TITLE
ERROR: create_app: Exception in /api/conversation cannot access local variable ' answer'  where it is not associated with a value

### ISSUE THREAD

**Issue by yaowilli** [Azure-Samples/chat-with-your-data-solution-accelerator#1302] opened 2024-09-09 14:31 UTC
# Describe the bug
This issue is observed when simply chatting with the chat App 
ERROR: create_app: Exception in /api/conversation cannot access local variable ' answer'  where it is not associated with a value
UnboundLoca1Error: cannot access local variable 'answer' where it is not associated with a value 

# Expected behavior
I would expect a clear answer with no error
---

# Debugging information

## Steps to reproduce
1.  by simply chatting with the App

## Screenshots
![image](https://github.com/user-attachments/assets/d2066c48-3bf3-4fcc-8486-e20bc9c6c575)
![image](https://github.com/user-attachments/assets/fb09825f-f4f0-484f-a0e5-70eb665afe98)

## Logs

ERROR: create_app: Exception in /api/conversation cannot access local variable ' answer'  where it is not associated with a value
UnboundLoca1Error: cannot access local variable 'answer' where it is not associated with a value 

---

# Tasks

_To be filled in by the engineer picking up the issue_

- [ ] Task 1
- [ ] Task 2
- [ ] ...

**Comment by Prasanjeet-Microsoft** [comment] 2024-09-12 09:45
Hello @yaowilli , Could you let us know about any other changes you made to the app settings before or after deployment?

FYI @Roopan-Microsoft

**Comment by yaowilli** [comment] 2024-09-12 19:11
@Prasanjeet-Microsoft  I made the following before : 

1/ disabled all public all public access 
2/ request for VNETs and 3 subnets 
3/ configure private end point s and the VNET integration ( is only for App service, function App/backend) 
     No end point for Key Vault 
4/ register DNS for private end point with intel cloud 
 --> after records added to DNS : do "nslookup " on each PE IP addresses to see if they resolve correctly 
5/ Roles assignment (Authenticate using RBAC) roles based access
6/

**Comment by Prasanjeet-Microsoft** [comment] 2024-09-13 11:35
Hello @yaowilli , Did you change the GPT model or make any other configuration changes in the application?

**Comment by yaowilli** [comment] 2024-09-13 16:50
@Prasanjeet-Microsoft  yes I changed the GPT to gpt-4o and embedding to text-embedding-ada-002
the settings are showing below 
![image](https://github.com/user-attachments/assets/89fe9844-08ac-48ea-a0e2-0a3ee310a595)
![image](https://github.com/user-attachments/assets/a87431a6-d6bd-4bfc-8b05-1d20508711fb)

USE_KEY_VAULT set to true

**Comment by Prasanjeet-Microsoft** [comment] 2024-09-16 19:08
Hello @yaowilli , This is to inform you that **text-embedding-ada-002** is the default value of Azure Open AI Embedding Model for this accelerator. However, we have tried to deploy this accelerator with gpt-4o model and have not been able to reproduce the issue so far.

Could you please provide the value of the AZURE_AUTH_TYPE environment variable from the app settings?

**Comment by yaowilli** [comment] 2024-09-16 19:43
The issue is sporadic it occurs when you do not expect it 
AZURE_AUTH_TYPE = keys

**Comment by Prasanjeet-Microsoft** [comment] 2024-09-18 11:06
Hello @yaowilli , Could you please investigate further using Application Insights to check for any exceptions or additional details? I believe there might be some relevant information that could help us diagnose the issue more precisely. Could you please follow the steps outlined below as an example.

**Go to Application Insights resource:**

<img width="934" alt="Screenshot 2024-09-18 153822" src="https://github.com/user-attachments/assets/7a877aa7-a76f-4328-8af2-b370120fecd0">

**In the Application Insights resource menu on the left, under Investigate, select the Failures option:**

<img width="947" alt="Screenshot 2024-09-18 153919" src="https://github.com/user-attachments/assets/f0e74cbb-2f2d-4b3d-a10a-c9c699e2fa14">

**Select the time range as Last 7 days or 30 days and click on Apply:**

<img width="935" alt="Screenshot 2024-09-18 153947" src="https://github.com/user-attachments/assets/0f273eb7-4674-4412-94c4-b8ed03702c47">

**Click on 500 response code:**

<img width="935" alt="Screenshot 2024-09-18 154244" src="https://github.com/user-attachments/assets/29efc1b6-dafe-4861-b0de-0df680cf7818">

**Click on suggested view details:**

<img width="941" alt="Screenshot 2024-09-18 154325" src="https://github.com/user-attachments/assets/d27c7c33-df35-4f1e-b35c-e07a9b1fa5da">

**Click on each exception and provide a screenshot for each one:**

<img width="927" alt="Screenshot 2024-09-18 154521" src="https://github.com/user-attachments/assets/48a5679c-475c-466a-9ccc-f5d9ca5cd97c">

**Comment by yaowilli** [comment] 2024-09-18 18:59
ok will do I am out of office at moment

**Comment by strudel0209** [comment] 2024-09-20 08:53
getting the same error after switching from Azure OpenAI model gpt-4 to gpt-4o - error is intermitent:

`` ERROR:create_app:Exception in /api/conversation/custom | cannot access local variable 'answer' where it is not associated with a value
2024-09-18T10:27:45.8196501Z Traceback (most recent call last):
2024-09-18T10:27:45.8196724Z   File "/usr/src/app/create_app.py", line 371, in conversation_custom
2024-09-18T10:27:45.8196849Z     messages = await message_orchestrator.handle_message(
2024-09-18T10:27:45.8196989Z                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-09-18T10:27:45.8197100Z   File "/usr/src/app/backend/batch/utilities/helpers/orchestrator_helper.py", line 27, in handle_message
2024-09-18T10:27:45.8197233Z     return await orchestrator.handle_message(
2024-09-18T10:27:45.8197359Z            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-09-18T10:27:45.8197464Z   File "/usr/src/app/backend/batch/utilities/orchestrator/orchestrator_base.py", line 72, in handle_message
2024-09-18T10:27:45.8197608Z     result = await self.orchestrate(user_message, chat_history, **kwargs)
2024-09-18T10:27:45.8197713Z              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-09-18T10:27:45.8197818Z   File "/usr/src/app/backend/batch/utilities/orchestrator/open_ai_functions.py", line 133, in orchestrate
2024-09-18T10:27:45.8197962Z     if response := self.call_content_safety_output(user_message, answer.answer):
2024-09-18T10:27:45.8198074Z                                                    ^^^^^^^^^^^^
2024-09-18T10:27:45.8198211Z UnboundLocalError: cannot access local variable 'answer' where it is not associated with a value
2024-09-18T10:27:45.8318921Z [pid: 1|app: 0|req: 25/25] 169.254.131.1 () {100 vars in 9602 bytes} [Wed Sep 18 10:27:43 2024] POST /api/conversation/custom => generated 77 bytes in 1870 msecs (HTTP/1.1 500) 2 headers in 90 bytes (2 switches on core 0)
2024-09-18 10:27:43.946 +00:00 [Information] Microsoft.AspNetCore.Hosting.Diagnostics: Request starting HTTP/1.1 POST http://omnicorechat.robotics.abb.com/api/conversation/custom - application/json 44300
2024-09-18 10:27:43.948 +00:00 [Information] MiddlewareConsoleLogs: {"Timestamp":"2024-09-18T10:27:43.9483332Z","SiteName":"web-gqbv7fgkgycfg-docker","TaskName":"TraceIO","Message":"Starting","ProviderName":"Microsoft-Azure-AppService-Middleware-Authentication","Level":4,"EventId":201,"ActivityId":"9ec2f6af-0cc6-40fe-853f-f43dddc06efd","ActionTaken":"TokenStore ReadContainer","Location":"FileSystem","TimeTaken":-1}
2024-09-18 10:27:43.959 +00:00 [Information] MiddlewareConsoleLogs: {"Timestamp":"2024-09-18T10:27:43.9594266Z","SiteName":"web-gqbv7fgkgycfg-docker","TaskName":"TraceIO","Message":"Completed","ProviderName":"Microsoft-Azure-AppService-Middleware-Authentication","Level":4,"EventId":201,"ActivityId":"9ec2f6af-0cc6-40fe-853f-f43dddc06efd","ActionTaken":"TokenStore ReadContainer","Location":"FileSystem","TimeTaken":11}
2024-09-18 10:27:43.959 +00:00 [Trace] Middleware: Request came in on normal port, sending to normal target http://169.254.131.3:80/api/conversation/custom
2024-09-18 10:27:43.959 +00:00 [Trace] Middleware: Forwarding request to http://169.254.131.3/api/conversation/custom
2024-09-18 10:27:43.960 +00:00 [Debug] Microsoft.AspNetCore.Server.Kestrel: Connection id "0HN6NPEEJVC93", Request id "0HN6NPEEJVC93:00000016": started reading request body.
2024-09-18 10:27:43.960 +00:00 [Debug] Microsoft.AspNetCore.Server.Kestrel: Connection id "0HN6NPEEJVC93", Request id "0HN6NPEEJVC93:00000016": done reading request body.
2024-09-18 10:27:45.832 +00:00 [Trace] Middleware: Forwarded request finished in 1872.279ms 200 INTERNAL SERVER ERROR ``

**Comment by Prasanjeet-Microsoft** [comment] 2024-09-24 20:59
@yaowilli We are already working on this, and the issue has been resolved. We will update you once it is published. 
Thank you.

**Comment by Prasanjeet-Microsoft** [comment] 2024-09-26 10:38
Hello @yaowilli , We would like to inform you that the code fix has been published. You can now redeploy the accelerator and run your tests. Please inform us once you’ve completed the testing so we can close this GitHub issue.

**Comment by yaowilli** [comment] 2024-09-26 13:09
Hi @Prasanjeet-Microsoft  is there a way I could obtain the code fixes via container deployment ?
my accelerator is already deployed and provisioned in Azure

**Comment by Prasanjeet-Microsoft** [comment] 2024-09-30 10:11
Hi @yaowilli, apologies for the delayed response. This accelerator already has container deployment in place, so there's no need to redeploy it. You can go ahead and run the test in your deployed accelerator. 
Please inform us once you’ve completed the testing, so we can close this issue. 

Thank you.

**Comment by yaowilli** [comment] 2024-10-01 19:39
I am sorry it seems to be working now thanks I was waiting to perform more testing

**Comment by Prasanjeet-Microsoft** [comment] 2024-10-03 10:58
> I am sorry it seems to be working now thanks I was waiting to perform more testing

@yaowilli Thank you for your confirmation. If your issue has been resolved, can we go ahead and close this issue?

**Comment by Prasanjeet-Microsoft** [comment] 2024-10-07 05:46
Hello @yaowilli, We are closing this issue now since it has already been fixed as part of PR https://github.com/Azure-Samples/chat-with-your-data-solution-accelerator/pull/1343. If you still encounter the issue, please feel free to reopen it. We're here to help if you need any assistance! 😄

**Closed by Prasanjeet-Microsoft** 2024-10-07 05:46 UTC
Labels: bug
