### ISSUE TITLE
Files ingested in Blob storage are NOT indexed in Search engine

### ISSUE THREAD

**Issue by Fractal2017** [Azure-Samples/chat-with-your-data-solution-accelerator#284] opened 2024-02-08 22:11 UTC
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ X ] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> Deploy the solution using One-Click deployment
> Wait until solution is completely deployed
> Use Admin page to load PDF into the solution
> PDF files are successfully uploaded into Blob storage container
> Though, There is no Document entries in Search Engine at all.

### Any log messages given by the failure
> None

### Expected/desired behavior
>Documents in Azure Search (Chunked)

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)
Windows 10

### Versions
>

### Mention any other details that might be useful
This issue exists during this week 5 or 6th Feb
> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by ross-p-smith** [comment] 2024-02-08 22:18
Hi - are you able to see if the message is in the Storage Queue? Has the Azure Function ran?

**Comment by Fractal2017** [comment] 2024-02-09 01:08
Function App 
it shows : failedCount = 45, operation_Name=batch_push_results
Container messages:
doc-processing-poison - It contains messages
Could I please have a guide where to look next? 
thanks

**Comment by komalg1** [comment] 2024-02-09 09:54
@Fractal2017 Can you please check for any exceptions in the application insights -> Transaction Search -> See logs for last 24 hours.

**Comment by Fractal2017** [comment] 2024-02-09 12:55
Indeed, I could see an error:

Exception while executing function: Functions.batch_push_results Result: Failure
Exception: RateLimitError: Requests to the Embeddings_Create Operation under Azure OpenAI API version 2023-07-01-preview have **exceeded call rate limit of your current OpenAI S0 pricing tier.** Please retry after 6 seconds. Please go here: https://aka.ms/oai/quotaincrease if you would like to further increase the default rate limit.
Stack:   File "/azure-functions-host/workers/python/3.11/LINUX/X64/azure_functions_worker/dispatcher.py", line 495, in _handle__invocation_request
    call_result = await self._loop.run_in_executor(

To add context, I have also deployed this solution in another resource group and one more solution (OpenAI Search Demo) all under the _same subscription_. 

I would appreciate a recommended action.

**Comment by ross-p-smith** [comment] 2024-02-09 13:56
Hi. The exception is that you have been rate limited. Are you sharing your OpenAI? How many files did you upload? If a lot, you need to scale up your Open AI

**Comment by Fractal2017** [comment] 2024-02-09 14:15
I have a **subscription ABC** under which I have created three resource groups:
- RG1: Sol 1 ( this repo)
-- Only 4 PDF documents 
- RG2: Sol 2 ( Azure OpenAI Search Demo - https://github.com/Azure-Samples/azure-search-openai-demo)
- - 44 PDF docs
- RG3: Sol 1 (this repo). I deployed again to test just in case something went wrong in the previous deployment for sol1.
- - No Documents (No document uploaded was indexed)

The average size of the PDFs are around 2MB and few are 6MB.

I deployed both solutions using default values: 
Hosting Plan: B3
Semantic Search: true (default is false)
GPT Mode: 3.5 (0613)
Embedding: Ada-002
Max Tokens: 1000
Cognitive Search : Standard

**Comment by komalg1** [comment] 2024-02-09 17:38
@Fractal2017 You can try increasing the quota for your open ai deployed model by going to AzureOpenAI Studio -> Deployments -> Edit Deployment.
<img width="605" alt="image" src="https://github.com/Azure-Samples/chat-with-your-data-solution-accelerator/assets/29505310/5d735b94-a166-4499-b846-2f8fe4a91a02">

If this also doesn't help, you may need to delete one of the open ai resource.

**Comment by DhammaParrot** [comment] 2024-02-15 09:34
Hi, I have the same issue. I am not sure how it can be related to call rate limit since I am ingesting 3 example pdfs from the data provided in this repo

**Comment by DhammaParrot** [comment] 2024-02-15 09:35
i mean yes call rate limit, but how if it's just three pdfs of total size around 2mb

**Comment by komalg1** [comment] 2024-02-15 11:19
Hi @DhammaParrot, Do you have another instance of the open ai resource created within same subscription?

**Comment by AndTraHTI** [comment] 2024-02-21 15:51
I have the same problem when deploying a new version. Has anyone perhaps found a solution for this?

**Comment by Lawndemon** [comment] 2024-03-08 22:19
If you navigate to Azure AI Studio, you can select "Quotas" to validate whether or not you have any remaining tokens. This will let you know if you issue is token related or, rather, something to do with you the API is being invoked.

**Comment by ross-p-smith** [comment] 2024-03-11 18:36
@Fractal2017 - is this still an issue? Do you think that this is something more than you do not have enough quota?

**Comment by Fractal2017** [comment] 2024-03-12 03:33
Apologies for the late response. I could not further test this environment since we had to deliver the solution in a short timeframe and in the end i had to recreate the resource group with only one OpenAI service.
So, this issue was not resolved to determine the root cause.
thanks

**Comment by ross-p-smith** [comment] 2024-03-12 21:26
I'm closing this as the exception was from the embeddings endpoint and around quota which is out of our control. It's also using the 2023-07-01-preview endpoint which we dont use anymore, so we wouldn't be able to reproduce. Please re-open if you come across this again. Thanks for reporting

**Closed by ross-p-smith** 2024-03-12 21:26 UTC
Labels: bug

**Comment by nh-lh** [comment] 2024-06-24 14:59
I am facing the same issue.

`Exception while executing function: Functions.batch_push_results Result: Failure
Exception: RateLimitError: Error code: 429 - {'error': {'code': '429', 'message': 'Requests to the Embeddings_Create Operation under Azure OpenAI API version 2024-02-01 have exceeded call rate limit of your current OpenAI S0 pricing tier. Please retry after 1 second. Please go here: https://aka.ms/oai/quotaincrease if you would like to further increase the default rate limit.'}}`

After this error occurred, I increased the TPM rate from 30 to 60 for the gpt-3 and ada-002 deployment. Now, the exception doesn't appear anymore, but the files that are appearing in "Delete Files" / Blob are still not being indexed. This started to happen after around 10 files have been indexed.
