### ISSUE TITLE
Continued issue with backend docker deployment

### ISSUE THREAD

**Issue by atockar** [Azure-Samples/chat-with-your-data-solution-accelerator#1266] opened 2024-08-30 06:44 UTC
Hi, I am still getting this issue. I have tried to deploy using the one click deployment and it fails in the same place, 
![Screenshot 2024-08-30 at 4 35 42 pm](https://github.com/user-attachments/assets/8529fc9a-3a32-4084-b5cb-639bd8a5ee2f)

I can see the bicep file has been updated in the code, and I added the storage blob data contributor role for the storage account to the function app:
> add the storage blob data contributor and storage data reader roles to the managed identity of the function app and ensure that when deploying solution you have in bicep file @Allowed(['Enabled', 'Disabled']) param publicNetworkAccess string = 'Enabled'

However when I redeploy this section it asks for the clientKey, which I thought was generated. Any ideas?

_Originally posted by @atockar in https://github.com/Azure-Samples/chat-with-your-data-solution-accelerator/issues/1195#issuecomment-2320236507_

**Comment by Roopan-Microsoft** [comment] 2024-09-03 05:00
Thanks @atockar for raising the issue, we are looking into this and will keep you posted.

**Comment by Roopan-Microsoft** [comment] 2024-09-04 04:26
Hey @atockar,

Could you please provide us with more details about the exception you’re encountering?

We’ve been able to deploy the accelerator successfully on our end, so we’d like to investigate further if you could share more information about the error you're experiencing.

**Comment by atockar** [comment] 2024-09-05 23:06
![Uploading Screenshot 2024-09-06 at 9.04.50 am.png…]()

I believe I found the source of the issue - it fails when I use a B1 hosting plan. See if you're able to replicate, thanks

**Comment by Roopan-Microsoft** [comment] 2024-09-06 04:01
Hey @atockar,
Thanks for finding out! I'll try replicating the issue with a B1 hosting plan and let you know what I find. I'll get back to you soon.

**Comment by Roopan-Microsoft** [comment] 2024-09-09 17:33
Yes @atockar, You are right! choosing this Sku plan throwing an error. We are looking into it. Thanks.

Meanwhile you can proceed with default Sku plans for now. We will update you on the root cause.

**Comment by TBunkley** [comment] 2024-09-18 17:35
I'm having issues with this. What are the default settings? Basic pops up first for me

**Comment by Roopan-Microsoft** [comment] 2024-09-18 18:17
Hey @TBunkley, Thanks for reaching out to us.

As you may know, the B1 plan includes one core, whereas the B3 plan offers four cores. Additionally, as shown in the screenshot below, we have less RAM, which is contributing to slower function app deployment. The default timeout is set to 300 seconds, resulting in failures.

We are currently looking into potential solutions for this issue.

<img width="667" alt="image" src="https://github.com/user-attachments/assets/d0b5c2b2-4d52-4c09-afaa-164b332e9cc6">

**Comment by Roopan-Microsoft** [comment] 2024-10-10 06:09
Hey @atockar / @TBunkle

When you select the deployment link, the hosting plan defaults to B3. Modifying this to use B1 will not function as expected, which is why a scale down operation does not resolve the issue.

Moreover, the solution you are implementing involves several services, including Azure App Service and Azure Speech Service, which require substantial memory. The B1 plan provides a small worker with 1.75 GB of RAM, whereas B3 offers a large worker with 7 GB of RAM.

Please don’t hesitate to reach out if you have any questions or concerns.

I'm closing this issue for now. Please feel free to reopen it if any problems arise. Happy to Help!

**Closed by Roopan-Microsoft** 2024-10-10 06:09 UTC
Labels: bug

**Comment by TBunkley** [comment] 2024-10-10 15:04
Thanks  @Roopan-Microsoft ,

Would it make sense to remove it as an option if it is a known case that fails? Maybe add a TODO for it?

**Comment by Roopan-Microsoft** [comment] 2024-10-10 16:05
> Thanks @Roopan-Microsoft ,
> 
> Would it make sense to remove it as an option if it is a known case that fails? Maybe add a TODO for it?

Yes @TBunkley . You are right! we will work on that and Thanks for your feedback.
