### ISSUE TITLE
One click deploy ->batch_start_processing function cant authenticate to storage.

### ISSUE THREAD

**Issue by andrewwiebe** [Azure-Samples/chat-with-your-data-solution-accelerator#204] opened 2024-01-17 18:14 UTC
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ x] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>Use one click deploy from the readme, all deployed resources show success. Upload file on admin site works correctly. When clicking the button to reprocess documents get an error from the batch_start_processing function.

### Any log messages given by the failure
>Below is the log message from the function.

2024-01-17T18:05:47Z   [Information]   Executing 'Functions.batch_start_processing' (Reason='This function was programmatically called via the host APIs.', Id=586608b5-40b8-4d41-85b2-452942c71f0e)
2024-01-17T18:05:47Z   [Verbose]   Sending invocation id: '586608b5-40b8-4d41-85b2-452942c71f0e
2024-01-17T18:05:47Z   [Verbose]   Posting invocation id:586608b5-40b8-4d41-85b2-452942c71f0e on workerId:87f3b8f6-6541-4854-abcb-41bcf9f3f5ae
2024-01-17T18:05:47Z   [Information]   Requested to start processing all documents received
2024-01-17T18:05:48Z   [Information]   No environment configuration found.
2024-01-17T18:05:48Z   [Information]   Request URL: 'http://169.254.169.254/metadata/identity/oauth2/token?api-version=REDACTED&resource=REDACTED'
Request method: 'GET'
Request headers:
    'User-Agent': 'azsdk-python-identity/1.15.0 Python/3.11.7 (Linux-5.15.131.1-2.cm2-x86_64-with-glibc2.31)'
No body was attached to the request
2024-01-17T18:05:48Z   [Information]   ManagedIdentityCredential will use IMDS
2024-01-17T18:05:48Z   [Warning]   DefaultAzureCredential failed to retrieve a token from the included credentials.
Attempted credentials:
	EnvironmentCredential: EnvironmentCredential authentication unavailable. Environment variables are not fully configured.
Visit https://aka.ms/azsdk/python/identity/environmentcredential/troubleshoot to troubleshoot this issue.
	ManagedIdentityCredential: ManagedIdentityCredential authentication unavailable, no response from the IMDS endpoint.
	AzureCliCredential: Azure CLI not found on path
	AzurePowerShellCredential: PowerShell is not installed
	AzureDeveloperCliCredential: Azure Developer CLI could not be found. Please visit https://aka.ms/azure-dev for installation instructions and then,once installed, authenticate to your Azure account using 'azd auth login'.
To mitigate this issue, please refer to the troubleshooting guidelines here at https://aka.ms/azsdk/python/identity/defaultazurecredential/troubleshoot.
2024-01-17T18:05:48Z   [Error]   Executed 'Functions.batch_start_processing' (Failed, Id=586608b5-40b8-4d41-85b2-452942c71f0e, Duration=211ms)

### Expected/desired behavior
> Processing the files from storage should function.

### OS and Version?
>

### Versions
>

### Mention any other details that might be useful

Obviously something going on with "No environment configuration found" but I can confirm the following config exists on the function app. Not sure why it doesn't seem to be reading these values.

![image](https://github.com/Azure-Samples/chat-with-your-data-solution-accelerator/assets/45373072/f95ecf3f-a488-447d-b06c-f1c95a4b4ffa)

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by ross-p-smith** [comment] 2024-01-17 18:53
Hi there - looking at the error; it talks about Managed Identity, so it may be configured to use `rbac` instead of `keys`. There has been a change in this area - let me try and reproduce for you.

**Comment by andrewwiebe** [comment] 2024-01-17 19:07
Is there anyway I can fall back to keys and environment setting for the auth just to get it working?

**Comment by thpickl** [comment] 2024-01-17 19:57
**One click deployment:** When uploading documents or clicking the button to reprocess documents throws an exception from the batch_push_results function.

Azure Function => batch_push_results | Monitor | Invocation Details:
_Result: Failure Exception: AuthenticationError: Principal does not have access to API/Operation. Stack: File "/azure-functions-host/workers/python/3.11/LINUX/X64/azure_functions_worker/dispatcher.py", line 495, in _handle__invocation_request call_result = await self._loop.run_in_executor( ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run result = self.fn(*self.args, **self.kwargs) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/azure-functions-host/workers/python/3.11/LINUX/X64/azure_functions_worker/dispatcher.py", line 768, in _run_sync_func return ExtensionManager.get_sync_invocation_wrapper(context, ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/azure-functions-host/workers/python/3.11/LINUX/X64/azure_functions_worker/extension.py", line 215, in _raw_invocation_wrapper result = function(**args) ^^^^^^^^^^^^^^^^ File "/home/site/wwwroot/BatchPushResults.py", line 30, in batch_push_results document_processor.process(source_url=file_sas, processors=processors) File "/home/site/wwwroot/utilities/helpers/DocumentProcessorHelper.py", line 22, in process vector_store = vector_store_helper.get_vector_store() ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/home/site/wwwroot/utilities/helpers/AzureSearchHelper.py", line 33, in get_vector_store vector_search_dimensions=len(llm_helper.get_embedding_model().embed_query("Text")), ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.11/site-packages/langchain/embeddings/openai.py", line 516, in embed_query return self.embed_documents([text])[0] ^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.11/site-packages/langchain/embeddings/openai.py", line 488, in embed_documents return self._get_len_safe_embeddings(texts, engine=self.deployment) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.11/site-packages/langchain/embeddings/openai.py", line 374, in _get_len_safe_embeddings response = embed_with_retry( ^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.11/site-packages/langchain/embeddings/openai.py", line 107, in embed_with_retry return _embed_with_retry(**kwargs) ^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.11/site-packages/tenacity/__init__.py", line 289, in wrapped_f return self(f, *args, **kw) ^^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.11/site-packages/tenacity/__init__.py", line 379, in __call__ do = self.iter(retry_state=retry_state) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.11/site-packages/tenacity/__init__.py", line 314, in iter return fut.result() ^^^^^^^^^^^^ File "/usr/local/lib/python3.11/concurrent/futures/_base.py", line 449, in result return self.__get_result() ^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.11/concurrent/futures/_base.py", line 401, in __get_result raise self._exception File "/usr/local/lib/python3.11/site-packages/tenacity/__init__.py", line 382, in __call__ result = fn(*args, **kwargs) ^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.11/site-packages/langchain/embeddings/openai.py", line 104, in _embed_with_retry response = embeddings.client.create(**kwargs) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.11/site-packages/openai/api_resources/embedding.py", line 33, in create response = super().create(*args, **kwargs) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.11/site-packages/openai/api_resources/abstract/engine_api_resource.py", line 153, in create response, _, api_key = requestor.request( ^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.11/site-packages/openai/api_requestor.py", line 298, in request resp, got_stream = self._interpret_response(result, stream) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.11/site-packages/openai/api_requestor.py", line 700, in _interpret_response self._interpret_response_line( File "/usr/local/lib/python3.11/site-packages/openai/api_requestor.py", line 763, in _interpret_response_line raise self.handle_error_response(_

**Comment by ross-p-smith** [comment] 2024-01-17 20:04
> Is there any documentation for how to deploy the devcontainer? I have never used it before.

Does this help: #205

**Comment by ross-p-smith** [comment] 2024-01-18 00:07
@andrewwiebe and @thpickl - can you retry - please let us know if this fix hasn't fixed things for you.

**Comment by andrewwiebe** [comment] 2024-01-18 14:59
I just deployed again but am still not able to see anything indexes in the search service. The auth error is gone and now I see the following in the functions log however the search index shows 0 documents and 0 bytes.

`2024-01-18T14:56:37Z   [Information]   Executing 'Functions.batch_start_processing' (Reason='This function was programmatically called via the host APIs.', Id=82cc5fcd-53d0-4704-a593-5f2349b271bb)
2024-01-18T14:56:37Z   [Verbose]   Sending invocation id: '82cc5fcd-53d0-4704-a593-5f2349b271bb
2024-01-18T14:56:37Z   [Verbose]   Posting invocation id:82cc5fcd-53d0-4704-a593-5f2349b271bb on workerId:b0a3f84a-e237-4745-aaf8-59a991bb3b15
2024-01-18T14:56:37Z   [Information]   Requested to start processing all documents received
2024-01-18T14:56:37Z   [Information]   No environment configuration found.
2024-01-18T14:56:37Z   [Information]   ManagedIdentityCredential will use App Service managed identity
2024-01-18T14:56:37Z   [Information]   Request URL: 'http://169.254.129.2:8081/msi/token?api-version=REDACTED&resource=REDACTED'
Request method: 'GET'
Request headers:
    'X-IDENTITY-HEADER': 'REDACTED'
    'User-Agent': 'azsdk-python-identity/1.15.0 Python/3.11.7 (Linux-5.15.131.1-2.cm2-x86_64-with-glibc2.31)'
No body was attached to the request
2024-01-18T14:56:37Z   [Information]   Response status: 200
Response headers:
    'Content-Type': 'application/json; charset=utf-8'
    'Date': 'Thu, 18 Jan 2024 14:56:36 GMT'
    'Server': 'Kestrel'
    'Transfer-Encoding': 'chunked'
    'X-CORRELATION-ID': 'REDACTED'
2024-01-18T14:56:37Z   [Information]   DefaultAzureCredential acquired a token from ManagedIdentityCredential
2024-01-18T14:56:37Z   [Information]   Request URL: 'https://aitutoracceldemostr.blob.core.windows.net/documents?restype=REDACTED&comp=REDACTED&include=REDACTED'
Request method: 'GET'
Request headers:
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.19.0 Python/3.11.7 (Linux-5.15.131.1-2.cm2-x86_64-with-glibc2.31)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': 'c79377e8-b611-11ee-9dbc-42de63a55d26'
    'Authorization': 'REDACTED'
No body was attached to the request
2024-01-18T14:56:37Z   [Information]   Response status: 200
Response headers:
    'Transfer-Encoding': 'chunked'
    'Content-Type': 'application/xml'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': '334d687a-001e-003b-251e-4a8f15000000'
    'x-ms-client-request-id': 'c79377e8-b611-11ee-9dbc-42de63a55d26'
    'x-ms-version': 'REDACTED'
    'Date': 'Thu, 18 Jan 2024 14:56:37 GMT'
2024-01-18T14:56:37Z   [Information]   Request URL: 'https://aitutoracceldemostr.queue.core.windows.net/doc-processing/messages'
Request method: 'POST'
Request headers:
    'Content-Length': '135'
    'x-ms-version': 'REDACTED'
    'Content-Type': 'application/xml'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-queue/12.9.0 Python/3.11.7 (Linux-5.15.131.1-2.cm2-x86_64-with-glibc2.31)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': 'c79caa0c-b611-11ee-9dbc-42de63a55d26'
    'Authorization': 'REDACTED'
A body is sent with the request
2024-01-18T14:56:38Z   [Information]   Response status: 201
Response headers:
    'Transfer-Encoding': 'chunked'
    'Content-Type': 'application/xml'
    'Server': 'Windows-Azure-Queue/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': '7f238243-3003-001f-791e-4a79b5000000'
    'x-ms-client-request-id': 'c79caa0c-b611-11ee-9dbc-42de63a55d26'
    'x-ms-version': 'REDACTED'
    'Date': 'Thu, 18 Jan 2024 14:56:37 GMT'
2024-01-18T14:56:38Z   [Information]   Executed 'Functions.batch_start_processing' (Succeeded, Id=82cc5fcd-53d0-4704-a593-5f2349b271bb, Duration=199ms)`

![image](https://github.com/Azure-Samples/chat-with-your-data-solution-accelerator/assets/45373072/b5ed1c4e-4f8e-41e5-b785-a9156f1a473d)

**Comment by komalg1** [comment] 2024-01-18 15:32
@andrewwiebe Can you try ingesting a very small size document? The AzureOpenAI API sometimes throttles if the document is too large. To prevent this could you please remove any unused AzureOpenAI resources (if any).

**Comment by andrewwiebe** [comment] 2024-01-18 15:58
> @andrewwiebe Can you try ingesting a very small size document? The AzureOpenAI API sometimes throttles if the document is too large. To prevent this could you please delete any unused AzureOpenAI resources (if any).

So I walked away for about 45 minutes for a meeting and when I came back it is showing up in the index now. Is there anyway to see the progress of the processing on any of the resources? Could you provide a quick flow of how things happen between when document lands in the storage and the index in the search service is complete?

**Comment by andrewwiebe** [comment] 2024-01-18 16:03
Also there is en error in the chat site now. There is auth failing, I assumse it is auth to the search service. Log below.

2024-01-18T16:01:22.438947118Z Analyze text failed.
2024-01-18T16:01:22.438991221Z Error code: 401
2024-01-18T16:01:22.438998521Z Error message: Access denied due to invalid subscription key or wrong API endpoint. Make sure to provide a valid key for an active subscription and use a correct regional API endpoint for your resource.
2024-01-18T16:01:22.447906979Z ERROR:root:Exception in /api/conversation/custom | (401) Access denied due to invalid subscription key or wrong API endpoint. Make sure to provide a valid key for an active subscription and use a correct regional API endpoint for your resource.
2024-01-18T16:01:22.447935381Z Code: 401
2024-01-18T16:01:22.447941682Z Message: Access denied due to invalid subscription key or wrong API endpoint. Make sure to provide a valid key for an active subscription and use a correct regional API endpoint for your resource.
2024-01-18T16:01:22.447946882Z Traceback (most recent call last):
2024-01-18T16:01:22.447951682Z   File "app.py", line 285, in conversation_custom
2024-01-18T16:01:22.447956382Z     messages = message_orchestrator.handle_message(user_message=user_message, chat_history=chat_history, conversation_id=conversation_id, orchestrator=ConfigHelper.get_active_config_or_default().orchestrator)
2024-01-18T16:01:22.447961283Z                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-01-18T16:01:22.447966283Z   File "/usr/src/app/utilities/helpers/OrchestratorHelper.py", line 13, in handle_message
2024-01-18T16:01:22.447970983Z     return orchestrator.handle_message(user_message, chat_history, conversation_id)
2024-01-18T16:01:22.447976584Z            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-01-18T16:01:22.447981484Z   File "/usr/src/app/utilities/orchestrator/OrchestratorBase.py", line 33, in handle_message
2024-01-18T16:01:22.447986184Z     result = self.orchestrate(user_message, chat_history, **kwargs)
2024-01-18T16:01:22.447990685Z              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-01-18T16:01:22.447995385Z   File "/usr/src/app/utilities/orchestrator/OpenAIFunctions.py", line 58, in orchestrate
2024-01-18T16:01:22.448000185Z     filtered_user_message = self.content_safety_checker.validate_input_and_replace_if_harmful(user_message)
2024-01-18T16:01:22.448004786Z                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-01-18T16:01:22.448009286Z   File "/usr/src/app/utilities/tools/ContentSafetyChecker.py", line 22, in validate_input_and_replace_if_harmful
2024-01-18T16:01:22.448013986Z     return self.process_answer(Answer(question="", answer=text, source_documents=[]), response_template=response_template).answer
2024-01-18T16:01:22.448019686Z            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-01-18T16:01:22.448036287Z   File "/usr/src/app/utilities/tools/ContentSafetyChecker.py", line 17, in process_answer
2024-01-18T16:01:22.448041188Z     answer.answer = self._filter_text_and_replace(answer.answer, response_template)
2024-01-18T16:01:22.448045688Z                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-01-18T16:01:22.448050188Z   File "/usr/src/app/utilities/tools/ContentSafetyChecker.py", line 31, in _filter_text_and_replace
2024-01-18T16:01:22.448054789Z     response = self.content_safety_client.analyze_text(request)
2024-01-18T16:01:22.448059189Z                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-01-18T16:01:22.448063689Z   File "/usr/local/lib/python3.11/site-packages/azure/core/tracing/decorator.py", line 78, in wrapper_use_tracer
2024-01-18T16:01:22.448068289Z     return func(*args, **kwargs)
2024-01-18T16:01:22.448072690Z            ^^^^^^^^^^^^^^^^^^^^^
2024-01-18T16:01:22.448077090Z   File "/usr/local/lib/python3.11/site-packages/azure/ai/contentsafety/_operations/_operations.py", line 413, in analyze_text
2024-01-18T16:01:22.448081790Z     map_error(status_code=response.status_code, response=response, error_map=error_map)
2024-01-18T16:01:22.448086191Z   File "/usr/local/lib/python3.11/site-packages/azure/core/exceptions.py", line 164, in map_error
2024-01-18T16:01:22.448090991Z     raise error

**Comment by komalg1** [comment] 2024-01-18 17:04
> Also there is en error in the chat site now. There is auth failing, I assume it is auth to the search service. Log below. This occurs when the /api/conversation/custom route is called.
> 
> 2024-01-18T16:01:22.438947118Z Analyze text failed. 2024-01-18T16:01:22.438991221Z Error code: 401 2024-01-18T16:01:22.438998521Z Error message: Access denied due to invalid subscription key or wrong API endpoint. Make sure to provide a valid key for an active subscription and use a correct regional API endpoint for your resource. 2024-01-18T16:01:22.447906979Z ERROR:root:Exception in /api/conversation/custom | (401) Access denied due to invalid subscription key or wrong API endpoint. Make sure to provide a valid key for an active subscription and use a correct regional API endpoint for your resource. 2024-01-18T16:01:22.447935381Z Code: 401 2024-01-18T16:01:22.447941682Z Message: Access denied due to invalid subscription key or wrong API endpoint. Make sure to provide a valid key for an active subscription and use a correct regional API endpoint for your resource. 2024-01-18T16:01:22.447946882Z Traceback (most recent call last): 2024-01-18T16:01:22.447951682Z File "app.py", line 285, in conversation_custom 2024-01-18T16:01:22.447956382Z messages = message_orchestrator.handle_message(user_message=user_message, chat_history=chat_history, conversation_id=conversation_id, orchestrator=ConfigHelper.get_active_config_or_default().orchestrator) 2024-01-18T16:01:22.447961283Z ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ 2024-01-18T16:01:22.447966283Z File "/usr/src/app/utilities/helpers/OrchestratorHelper.py", line 13, in handle_message 2024-01-18T16:01:22.447970983Z return orchestrator.handle_message(user_message, chat_history, conversation_id) 2024-01-18T16:01:22.447976584Z ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ 2024-01-18T16:01:22.447981484Z File "/usr/src/app/utilities/orchestrator/OrchestratorBase.py", line 33, in handle_message 2024-01-18T16:01:22.447986184Z result = self.orchestrate(user_message, chat_history, **kwargs) 2024-01-18T16:01:22.447990685Z ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ 2024-01-18T16:01:22.447995385Z File "/usr/src/app/utilities/orchestrator/OpenAIFunctions.py", line 58, in orchestrate 2024-01-18T16:01:22.448000185Z filtered_user_message = self.content_safety_checker.validate_input_and_replace_if_harmful(user_message) 2024-01-18T16:01:22.448004786Z ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ 2024-01-18T16:01:22.448009286Z File "/usr/src/app/utilities/tools/ContentSafetyChecker.py", line 22, in validate_input_and_replace_if_harmful 2024-01-18T16:01:22.448013986Z return self.process_answer(Answer(question="", answer=text, source_documents=[]), response_template=response_template).answer 2024-01-18T16:01:22.448019686Z ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ 2024-01-18T16:01:22.448036287Z File "/usr/src/app/utilities/tools/ContentSafetyChecker.py", line 17, in process_answer 2024-01-18T16:01:22.448041188Z answer.answer = self._filter_text_and_replace(answer.answer, response_template) 2024-01-18T16:01:22.448045688Z ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ 2024-01-18T16:01:22.448050188Z File "/usr/src/app/utilities/tools/ContentSafetyChecker.py", line 31, in _filter_text_and_replace 2024-01-18T16:01:22.448054789Z response = self.content_safety_client.analyze_text(request) 2024-01-18T16:01:22.448059189Z ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ 2024-01-18T16:01:22.448063689Z File "/usr/local/lib/python3.11/site-packages/azure/core/tracing/decorator.py", line 78, in wrapper_use_tracer 2024-01-18T16:01:22.448068289Z return func(*args, **kwargs) 2024-01-18T16:01:22.448072690Z ^^^^^^^^^^^^^^^^^^^^^ 2024-01-18T16:01:22.448077090Z File "/usr/local/lib/python3.11/site-packages/azure/ai/contentsafety/_operations/_operations.py", line 413, in analyze_text 2024-01-18T16:01:22.448081790Z map_error(status_code=response.status_code, response=response, error_map=error_map) 2024-01-18T16:01:22.448086191Z File "/usr/local/lib/python3.11/site-packages/azure/core/exceptions.py", line 164, in map_error 2024-01-18T16:01:22.448090991Z raise error

@andrewwiebe I am not able to reproduce this issue. One-click deploy chat also worked for me. Did you deploy using keys or rbac? Can you please clear cache, refresh and check? Sometimes there is a token cache issue which may cause this.

**Comment by ross-p-smith** [comment] 2024-01-18 17:30
I've just deployed a fresh "One Click Deploy" and the `api/conversation/custom` route works for me too. @andrewwiebe - I'm going to close this one as the original bug is fixed. Please do raise a new one though if you find any auth problems after you have deployed a fresh install. Thank you for bearing with us whilst we secure the application with RBAC rather than keys.

**Closed by ross-p-smith** 2024-01-18 17:30 UTC
Labels: bug, python
